"""Abstract base class for schema generators.

Every generator must produce output in a protocol-specific directory inside
the workspace and include a header comment referencing the Linear issue identifier.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import TYPE_CHECKING

import structlog

if TYPE_CHECKING:
    from pathlib import Path

    from uptempo.tracker.models import Issue

logger = structlog.get_logger(__name__)


class SchemaGenerator(ABC):
    """Base class that all schema generators must implement."""

    @abstractmethod
    def generate(self, issue: Issue, workspace: Path) -> list[Path]:
        """Generate schema files for *issue* inside *workspace*.

        Returns the list of created file paths.
        """
        ...

    @abstractmethod
    def validate(self, files: list[Path]) -> list[str]:
        """Validate generated *files* and return a list of error messages (empty on success)."""
        ...

    def _header_comment(self, issue: Issue, comment_prefix: str = "#") -> str:
        """Standard header comment referencing the source issue."""
        return f"{comment_prefix} Generated by Uptempo for {issue.identifier}: {issue.title}"
