"""OpenAPI 3.1 YAML schema generator.

Output is placed in ``<workspace>/openapi/`` and validated with Spectral.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import structlog
import yaml

from uptempo.schema._common import issue_stem, issue_summary, pascal_case
from uptempo.schema.base import SchemaGenerator

if TYPE_CHECKING:
    from pathlib import Path

    from uptempo.tracker.models import Issue

logger = structlog.get_logger(__name__)


class OpenApiGenerator(SchemaGenerator):
    """Generate OpenAPI 3.1 YAML specifications."""

    def generate(self, issue: Issue, workspace: Path) -> list[Path]:
        output_dir = workspace / "openapi"
        output_dir.mkdir(parents=True, exist_ok=True)

        stem = issue_stem(issue)
        entity_name = pascal_case(stem)
        path_name = f"/{stem}"
        file_path = output_dir / f"{stem}.yaml"
        summary = issue_summary(issue)

        spec = {
            "openapi": "3.1.0",
            "info": {
                "title": issue.title,
                "version": "0.1.0",
                "summary": summary,
                "description": f"Generated from issue {issue.identifier}.",
            },
            "paths": {
                path_name: {
                    "get": {
                        "operationId": f"get{entity_name}",
                        "summary": summary,
                        "responses": {
                            "200": {
                                "description": f"Successful {entity_name} response",
                                "content": {
                                    "application/json": {
                                        "schema": {
                                            "$ref": f"#/components/schemas/{entity_name}Response"
                                        }
                                    }
                                },
                            }
                        },
                    }
                }
            },
            "components": {
                "schemas": {
                    entity_name: {
                        "type": "object",
                        "properties": {
                            "id": {"type": "string"},
                            "title": {"type": "string", "example": issue.title},
                            "description": {"type": "string", "example": summary},
                        },
                        "required": ["id", "title"],
                    },
                    f"{entity_name}Response": {
                        "type": "object",
                        "properties": {
                            "data": {"$ref": f"#/components/schemas/{entity_name}"},
                            "issue": {"type": "string", "example": issue.identifier},
                        },
                        "required": ["data", "issue"],
                    },
                }
            },
        }

        contents = f"{self._header_comment(issue)}\n" + yaml.safe_dump(
            spec, sort_keys=False, allow_unicode=True
        )
        file_path.write_text(contents)
        logger.info("generated_openapi_schema", issue_id=issue.identifier, path=str(file_path))
        return [file_path]

    def validate(self, files: list[Path]) -> list[str]:
        errors: list[str] = []

        for file_path in files:
            if not file_path.exists():
                errors.append(f"{file_path}: file does not exist")
                continue

            if file_path.suffix not in {".yaml", ".yml"}:
                errors.append(f"{file_path}: expected a YAML file")
                continue

            contents = file_path.read_text()
            if not contents.startswith("# Generated by Uptempo for "):
                errors.append(f"{file_path}: missing generated header comment")

            try:
                document = yaml.safe_load(contents)
            except yaml.YAMLError as exc:
                errors.append(f"{file_path}: invalid YAML: {exc}")
                continue

            if not isinstance(document, dict):
                errors.append(f"{file_path}: expected a YAML mapping")
                continue

            if not str(document.get("openapi", "")).startswith("3.1"):
                errors.append(f"{file_path}: missing OpenAPI 3.1 version")

            info = document.get("info")
            if not isinstance(info, dict) or not info.get("title") or not info.get("version"):
                errors.append(f"{file_path}: missing info.title or info.version")

            paths = document.get("paths")
            if not isinstance(paths, dict) or not paths:
                errors.append(f"{file_path}: missing paths")
                continue

            for path_item in paths.values():
                if not isinstance(path_item, dict) or not path_item:
                    errors.append(f"{file_path}: invalid path item")
                    break

                operations = [
                    operation
                    for method, operation in path_item.items()
                    if method in {"get", "post", "put", "patch", "delete"}
                ]
                if not operations:
                    errors.append(f"{file_path}: path item missing HTTP operation")
                    break

                if not all(
                    isinstance(operation, dict) and isinstance(operation.get("responses"), dict)
                    for operation in operations
                ):
                    errors.append(f"{file_path}: operation missing responses")
                    break

        return errors
