"""Protobuf (proto3) schema generator.

Output is placed in ``<workspace>/proto/`` and validated with ``buf lint``.
Language-specific options (``go_package``, ``java_package``) are included
when the issue specifies a target language.
"""

from __future__ import annotations

import re
from collections.abc import Callable
from typing import TYPE_CHECKING

import structlog

from uptempo.schema._common import issue_stem, issue_summary, pascal_case, snake_case
from uptempo.schema.base import SchemaGenerator

if TYPE_CHECKING:
    from pathlib import Path

    from uptempo.tracker.models import Issue

logger = structlog.get_logger(__name__)

OptionFactory = Callable[[str, str], str]

_TARGET_LANGUAGE_OPTIONS: dict[str, OptionFactory] = {
    "go": lambda package, service: f'option go_package = "github.com/uptempo/generated/{package};{service}";',
    "golang": lambda package, service: f'option go_package = "github.com/uptempo/generated/{package};{service}";',
    "java": lambda package, _service: f'option java_package = "com.uptempo.generated.{package}";',
}


class ProtoGenerator(SchemaGenerator):
    """Generate proto3 ``.proto`` files."""

    def generate(self, issue: Issue, workspace: Path) -> list[Path]:
        output_dir = workspace / "proto"
        output_dir.mkdir(parents=True, exist_ok=True)

        stem = issue_stem(issue)
        package_name = snake_case(stem)
        entity_name = pascal_case(stem)
        service_name = f"{entity_name}Service"
        request_name = f"{entity_name}Request"
        response_name = f"{entity_name}Response"
        file_path = output_dir / f"{stem}.proto"
        summary = issue_summary(issue)
        option_lines = self._language_options(issue, package_name, entity_name)

        lines = [
            self._header_comment(issue, comment_prefix="//"),
            'syntax = "proto3";',
            "",
            f"package {package_name};",
            *option_lines,
            "",
            f"service {service_name} {{",
            f"  rpc Get{entity_name} ({request_name}) returns ({response_name});",
            "}",
            "",
            f"message {request_name} {{",
            "  string issue_id = 1;",
            "}",
            "",
            f"message {response_name} {{",
            "  string issue_id = 1;",
            f"  string summary = 2;  // {summary}",
            "}",
        ]

        file_path.write_text("\n".join(lines) + "\n")
        logger.info("generated_proto_schema", issue_id=issue.identifier, path=str(file_path))
        return [file_path]

    def validate(self, files: list[Path]) -> list[str]:
        errors: list[str] = []

        for file_path in files:
            if not file_path.exists():
                errors.append(f"{file_path}: file does not exist")
                continue

            if file_path.suffix != ".proto":
                errors.append(f"{file_path}: expected a .proto file")
                continue

            contents = file_path.read_text()
            if not contents.startswith("// Generated by Uptempo for "):
                errors.append(f"{file_path}: missing generated header comment")

            if 'syntax = "proto3";' not in contents:
                errors.append(f"{file_path}: missing proto3 syntax declaration")

            if not re.search(r"^package\s+[a-z0-9_]+;$", contents, flags=re.MULTILINE):
                errors.append(f"{file_path}: missing package declaration")

            if not re.search(r"^service\s+\w+\s*\{", contents, flags=re.MULTILINE):
                errors.append(f"{file_path}: missing service definition")

            if len(re.findall(r"^message\s+\w+\s*\{", contents, flags=re.MULTILINE)) < 2:
                errors.append(f"{file_path}: expected at least two message definitions")

            if contents.count("{") != contents.count("}"):
                errors.append(f"{file_path}: unbalanced braces")

        return errors

    def _language_options(self, issue: Issue, package_name: str, service_name: str) -> list[str]:
        issue_text = " ".join(
            [
                issue.title,
                issue.description,
                *(label.name for label in issue.labels),
            ]
        ).lower()
        options = [
            option_factory(package_name, service_name)
            for language, option_factory in _TARGET_LANGUAGE_OPTIONS.items()
            if language in issue_text
        ]
        return [*options, ""] if options else []
