"""Thrift IDL schema generator.

Output is placed in ``<workspace>/thrift/``.
"""

from __future__ import annotations

import re
from typing import TYPE_CHECKING

import structlog

from uptempo.schema._common import issue_stem, issue_summary, pascal_case, snake_case
from uptempo.schema.base import SchemaGenerator

if TYPE_CHECKING:
    from pathlib import Path

    from uptempo.tracker.models import Issue

logger = structlog.get_logger(__name__)


class ThriftGenerator(SchemaGenerator):
    """Generate ``.thrift`` IDL files."""

    def generate(self, issue: Issue, workspace: Path) -> list[Path]:
        output_dir = workspace / "thrift"
        output_dir.mkdir(parents=True, exist_ok=True)

        stem = issue_stem(issue)
        namespace = snake_case(stem)
        entity_name = pascal_case(stem)
        request_name = f"{entity_name}Request"
        response_name = f"{entity_name}Response"
        service_name = f"{entity_name}Service"
        file_path = output_dir / f"{stem}.thrift"
        summary = _escape_thrift_string(issue_summary(issue))

        contents = "\n".join(
            [
                self._header_comment(issue, comment_prefix="//"),
                f"namespace py uptempo.generated.{namespace}",
                "",
                f"struct {request_name} {{",
                "  1: string issue_id",
                "}",
                "",
                f"struct {response_name} {{",
                "  1: string issue_id",
                f'  2: string summary = "{summary}"',
                "}",
                "",
                f"service {service_name} {{",
                f"  {response_name} get{entity_name}(1: {request_name} request)",
                "}",
                "",
            ]
        )

        file_path.write_text(contents)
        logger.info("generated_thrift_schema", issue_id=issue.identifier, path=str(file_path))
        return [file_path]

    def validate(self, files: list[Path]) -> list[str]:
        errors: list[str] = []

        for file_path in files:
            if not file_path.exists():
                errors.append(f"{file_path}: file does not exist")
                continue

            if file_path.suffix != ".thrift":
                errors.append(f"{file_path}: expected a .thrift file")
                continue

            contents = file_path.read_text()
            if not contents.startswith("// Generated by Uptempo for "):
                errors.append(f"{file_path}: missing generated header comment")

            if not re.search(r"^namespace\s+\w+\s+[\w.]+$", contents, flags=re.MULTILINE):
                errors.append(f"{file_path}: missing namespace declaration")

            if len(re.findall(r"^struct\s+\w+\s*\{", contents, flags=re.MULTILINE)) < 2:
                errors.append(f"{file_path}: expected at least two struct definitions")

            if not re.search(r"^service\s+\w+\s*\{", contents, flags=re.MULTILINE):
                errors.append(f"{file_path}: missing service definition")

            summary_match = re.search(
                r'^\s*\d+:\s+string\s+summary\s+=\s+"(?:[^"\\]|\\.)*"$',
                contents,
                flags=re.MULTILINE,
            )
            if summary_match is None:
                errors.append(f"{file_path}: invalid Thrift string literal for summary")

            if contents.count("{") != contents.count("}"):
                errors.append(f"{file_path}: unbalanced braces")

        return errors


def _escape_thrift_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')
