"""AsyncAPI 3.0 YAML / JSON Schema generator for WebSocket protocols.

Output is placed in ``<workspace>/websocket/``.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import structlog
import yaml

from uptempo.schema._common import issue_stem, issue_summary, pascal_case
from uptempo.schema.base import SchemaGenerator

if TYPE_CHECKING:
    from pathlib import Path

    from uptempo.tracker.models import Issue

logger = structlog.get_logger(__name__)


class WebSocketGenerator(SchemaGenerator):
    """Generate AsyncAPI 3.0 YAML or JSON Schema files."""

    def generate(self, issue: Issue, workspace: Path) -> list[Path]:
        output_dir = workspace / "websocket"
        output_dir.mkdir(parents=True, exist_ok=True)

        stem = issue_stem(issue)
        entity_name = pascal_case(stem)
        channel_name = f"{stem}-channel"
        message_name = f"{entity_name}Message"
        file_path = output_dir / f"{stem}.yaml"
        summary = issue_summary(issue)

        spec = {
            "asyncapi": "3.0.0",
            "info": {
                "title": issue.title,
                "version": "0.1.0",
                "description": f"Generated from issue {issue.identifier}.",
            },
            "channels": {
                channel_name: {
                    "address": f"/ws/{stem}",
                    "messages": {message_name: {"$ref": f"#/components/messages/{message_name}"}},
                }
            },
            "operations": {
                f"receive{entity_name}": {
                    "action": "receive",
                    "channel": {"$ref": f"#/channels/{channel_name}"},
                    "messages": [f"#/channels/{channel_name}/messages/{message_name}"],
                }
            },
            "components": {
                "messages": {
                    message_name: {
                        "name": f"{stem}.message",
                        "title": message_name,
                        "payload": {"$ref": f"#/components/schemas/{entity_name}Payload"},
                    }
                },
                "schemas": {
                    f"{entity_name}Payload": {
                        "type": "object",
                        "properties": {
                            "issue": {"type": "string", "const": issue.identifier},
                            "summary": {"type": "string", "default": summary},
                        },
                        "required": ["issue", "summary"],
                    }
                },
            },
        }

        contents = f"{self._header_comment(issue)}\n" + yaml.safe_dump(
            spec, sort_keys=False, allow_unicode=True
        )
        file_path.write_text(contents)
        logger.info("generated_websocket_schema", issue_id=issue.identifier, path=str(file_path))
        return [file_path]

    def validate(self, files: list[Path]) -> list[str]:
        errors: list[str] = []

        for file_path in files:
            if not file_path.exists():
                errors.append(f"{file_path}: file does not exist")
                continue

            if file_path.suffix not in {".yaml", ".yml"}:
                errors.append(f"{file_path}: expected a YAML file")
                continue

            contents = file_path.read_text()
            if not contents.startswith("# Generated by Uptempo for "):
                errors.append(f"{file_path}: missing generated header comment")

            try:
                document = yaml.safe_load(contents)
            except yaml.YAMLError as exc:
                errors.append(f"{file_path}: invalid YAML: {exc}")
                continue

            if not isinstance(document, dict):
                errors.append(f"{file_path}: expected a YAML mapping")
                continue

            if not str(document.get("asyncapi", "")).startswith("3.0"):
                errors.append(f"{file_path}: missing AsyncAPI 3.0 version")

            channels = document.get("channels")
            if not isinstance(channels, dict) or not channels:
                errors.append(f"{file_path}: missing channels")

            operations = document.get("operations")
            if not isinstance(operations, dict) or not operations:
                errors.append(f"{file_path}: missing operations")
            elif not all(
                isinstance(operation, dict)
                and operation.get("action") in {"send", "receive"}
                and operation.get("channel")
                for operation in operations.values()
            ):
                errors.append(f"{file_path}: invalid operation definitions")

            components = document.get("components")
            if not isinstance(components, dict):
                errors.append(f"{file_path}: missing components")
                continue

            messages = components.get("messages")
            if not isinstance(messages, dict) or not messages:
                errors.append(f"{file_path}: missing component messages")

            schemas = components.get("schemas")
            if not isinstance(schemas, dict) or not schemas:
                errors.append(f"{file_path}: missing component schemas")

        return errors
