"""Focused tests for the four foundational schema generators."""

from __future__ import annotations

from typing import TYPE_CHECKING

import yaml

from uptempo.schema.openapi import OpenApiGenerator
from uptempo.schema.proto import ProtoGenerator
from uptempo.schema.thrift import ThriftGenerator
from uptempo.schema.websocket import WebSocketGenerator
from uptempo.tracker.models import Issue, Label

if TYPE_CHECKING:
    from pathlib import Path


def _sample_issue() -> Issue:
    return Issue(
        id="issue-7",
        identifier="UP-7",
        title="Create user endpoints",
        description="CRUD API for user management over HTTP and WebSocket.",
        state="Todo",
        labels=[Label(id="label-api", name="api")],
    )


def test_openapi_generate_and_validate(tmp_workspace: Path) -> None:
    generator = OpenApiGenerator()
    issue = _sample_issue()

    files = generator.generate(issue, tmp_workspace)

    assert len(files) == 1
    assert files[0].parent == tmp_workspace / "openapi"
    contents = files[0].read_text()
    assert contents.startswith("# Generated by Uptempo for UP-7: Create user endpoints")

    document = yaml.safe_load(contents)
    assert document["openapi"] == "3.1.0"
    assert "/user-endpoints" in document["paths"]
    assert "UserEndpointsResponse" in document["components"]["schemas"]
    assert generator.validate(files) == []


def test_openapi_validate_rejects_missing_fields(tmp_workspace: Path) -> None:
    invalid_file = tmp_workspace / "openapi" / "invalid.yaml"
    invalid_file.parent.mkdir(parents=True, exist_ok=True)
    invalid_file.write_text("# Generated by Uptempo for UP-7: Create user endpoints\ninfo: {}\n")

    errors = OpenApiGenerator().validate([invalid_file, invalid_file.parent / "missing.yaml"])

    assert any("missing OpenAPI 3.1 version" in error for error in errors)
    assert any("file does not exist" in error for error in errors)


def test_proto_generate_and_validate(tmp_workspace: Path) -> None:
    generator = ProtoGenerator()
    issue = Issue(
        id="issue-7",
        identifier="UP-7",
        title="Create user endpoints",
        description="CRUD API for user management with Go clients.",
        state="Todo",
        labels=[Label(id="label-go", name="go")],
    )

    files = generator.generate(issue, tmp_workspace)

    assert len(files) == 1
    assert files[0].parent == tmp_workspace / "proto"
    contents = files[0].read_text()
    assert contents.startswith("// Generated by Uptempo for UP-7: Create user endpoints")
    assert 'syntax = "proto3";' in contents
    assert "package user_endpoints;" in contents
    assert (
        'option go_package = "github.com/uptempo/generated/user_endpoints;UserEndpoints";'
        in contents
    )
    assert "service UserEndpointsService" in contents
    assert generator.validate(files) == []


def test_proto_validate_rejects_invalid_files(tmp_workspace: Path) -> None:
    invalid_file = tmp_workspace / "proto" / "invalid.proto"
    invalid_file.parent.mkdir(parents=True, exist_ok=True)
    invalid_file.write_text(
        "// Generated by Uptempo for UP-7: Create user endpoints\npackage broken;\n"
    )

    errors = ProtoGenerator().validate([invalid_file, invalid_file.parent / "missing.proto"])

    assert any("missing proto3 syntax declaration" in error for error in errors)
    assert any("missing service definition" in error for error in errors)
    assert any("file does not exist" in error for error in errors)


def test_thrift_generate_and_validate(tmp_workspace: Path) -> None:
    generator = ThriftGenerator()
    issue = _sample_issue()

    files = generator.generate(issue, tmp_workspace)

    assert len(files) == 1
    assert files[0].parent == tmp_workspace / "thrift"
    contents = files[0].read_text()
    assert contents.startswith("// Generated by Uptempo for UP-7: Create user endpoints")
    assert "namespace py uptempo.generated.user_endpoints" in contents
    assert "struct UserEndpointsRequest" in contents
    assert "service UserEndpointsService" in contents
    assert generator.validate(files) == []


def test_thrift_validate_rejects_invalid_files(tmp_workspace: Path) -> None:
    invalid_file = tmp_workspace / "thrift" / "invalid.thrift"
    invalid_file.parent.mkdir(parents=True, exist_ok=True)
    invalid_file.write_text(
        "// Generated by Uptempo for UP-7: Create user endpoints\nstruct Broken {\n"
    )

    errors = ThriftGenerator().validate([invalid_file, invalid_file.parent / "missing.thrift"])

    assert any("missing namespace declaration" in error for error in errors)
    assert any("unbalanced braces" in error for error in errors)
    assert any("file does not exist" in error for error in errors)


def test_thrift_generate_escapes_quotes_in_summary(tmp_workspace: Path) -> None:
    generator = ThriftGenerator()
    issue = Issue(
        id="issue-quote",
        identifier="UP-8",
        title='API endpoint for "user" resources',
        description='Expose "user" summary fields.',
        state="Todo",
        labels=[],
    )

    [file_path] = generator.generate(issue, tmp_workspace)
    contents = file_path.read_text()

    assert '\\"user\\"' in contents
    assert generator.validate([file_path]) == []


def test_websocket_generate_and_validate(tmp_workspace: Path) -> None:
    generator = WebSocketGenerator()
    issue = _sample_issue()

    files = generator.generate(issue, tmp_workspace)

    assert len(files) == 1
    assert files[0].parent == tmp_workspace / "websocket"
    contents = files[0].read_text()
    assert contents.startswith("# Generated by Uptempo for UP-7: Create user endpoints")

    document = yaml.safe_load(contents)
    assert document["asyncapi"] == "3.0.0"
    assert "user-endpoints-channel" in document["channels"]
    assert "receiveUserEndpoints" in document["operations"]
    assert "UserEndpointsPayload" in document["components"]["schemas"]
    assert generator.validate(files) == []


def test_websocket_validate_rejects_invalid_files(tmp_workspace: Path) -> None:
    invalid_file = tmp_workspace / "websocket" / "invalid.yaml"
    invalid_file.parent.mkdir(parents=True, exist_ok=True)
    invalid_file.write_text(
        "# Generated by Uptempo for UP-7: Create user endpoints\nasyncapi: 3.0.0\nchannels: {}\n"
    )

    errors = WebSocketGenerator().validate([invalid_file, invalid_file.parent / "missing.yaml"])

    assert any("missing operations" in error for error in errors)
    assert any("missing components" in error for error in errors)
    assert any("file does not exist" in error for error in errors)
