"""Tests for schema generator instantiation and interface compliance."""

from __future__ import annotations

import importlib
from typing import TYPE_CHECKING

import pytest

from uptempo.schema.base import SchemaGenerator
from uptempo.tracker.models import Issue, Label

if TYPE_CHECKING:
    from pathlib import Path

GENERATORS = [
    ("uptempo.schema.openapi", "OpenApiGenerator"),
    ("uptempo.schema.proto", "ProtoGenerator"),
    ("uptempo.schema.thrift", "ThriftGenerator"),
    ("uptempo.schema.websocket", "WebSocketGenerator"),
    ("uptempo.schema.sse", "SseGenerator"),
    ("uptempo.schema.graphql", "GraphQlGenerator"),
    ("uptempo.schema.event", "EventSchemaGenerator"),
    ("uptempo.schema.webhook", "WebhookGenerator"),
    ("uptempo.schema.mqtt", "MqttGenerator"),
    ("uptempo.schema.trpc", "TrpcGenerator"),
]

_IDS = [name for _, name in GENERATORS]


def _load_class(module_path: str, class_name: str) -> type:
    """Import *class_name* from *module_path* and return the class."""
    mod = importlib.import_module(module_path)
    return getattr(mod, class_name)


@pytest.fixture()
def sample_issue() -> Issue:
    """Minimal Issue used for interface tests."""
    return Issue(
        id="issue-1",
        identifier="UP-42",
        title="Create user endpoints",
        description="CRUD API for user management",
        state="In Progress",
        labels=[Label(id="lbl-1", name="api")],
    )


# ------------------------------------------------------------------
# Instantiation & inheritance
# ------------------------------------------------------------------


@pytest.mark.parametrize(("module_path", "class_name"), GENERATORS, ids=_IDS)
def test_generator_is_instantiable(module_path: str, class_name: str) -> None:
    cls = _load_class(module_path, class_name)
    instance = cls()
    assert instance is not None


@pytest.mark.parametrize(("module_path", "class_name"), GENERATORS, ids=_IDS)
def test_generator_inherits_from_base(module_path: str, class_name: str) -> None:
    cls = _load_class(module_path, class_name)
    assert issubclass(cls, SchemaGenerator)


# ------------------------------------------------------------------
# Abstract method stubs raise NotImplementedError
# ------------------------------------------------------------------


@pytest.mark.parametrize(("module_path", "class_name"), GENERATORS, ids=_IDS)
def test_generate_raises_not_implemented(
    module_path: str,
    class_name: str,
    sample_issue: Issue,
    tmp_path: Path,
) -> None:
    cls = _load_class(module_path, class_name)
    instance = cls()
    with pytest.raises(NotImplementedError):
        instance.generate(sample_issue, tmp_path)


@pytest.mark.parametrize(("module_path", "class_name"), GENERATORS, ids=_IDS)
def test_validate_raises_not_implemented(
    module_path: str,
    class_name: str,
) -> None:
    cls = _load_class(module_path, class_name)
    instance = cls()
    with pytest.raises(NotImplementedError):
        instance.validate([])


# ------------------------------------------------------------------
# _header_comment
# ------------------------------------------------------------------


@pytest.mark.parametrize(("module_path", "class_name"), GENERATORS, ids=_IDS)
def test_header_comment_default_prefix(
    module_path: str,
    class_name: str,
    sample_issue: Issue,
) -> None:
    cls = _load_class(module_path, class_name)
    instance = cls()
    header = instance._header_comment(sample_issue)
    assert header == "# Generated by Uptempo for UP-42: Create user endpoints"


@pytest.mark.parametrize(("module_path", "class_name"), GENERATORS, ids=_IDS)
def test_header_comment_custom_prefix(
    module_path: str,
    class_name: str,
    sample_issue: Issue,
) -> None:
    cls = _load_class(module_path, class_name)
    instance = cls()
    header = instance._header_comment(sample_issue, comment_prefix="//")
    assert header == "// Generated by Uptempo for UP-42: Create user endpoints"
